<table>
    <tr>
        <th class="grid-name"> <a href='http://127.0.0.1/magento/mrcareers/job/info/'>Name</a></th>
        <th class="grid-short_description">Short Description</th>
    </tr>
    <?php
    foreach ($block->getGridCollection() as $key=>$grid){
        echo '<tr>
                    <td>'.$grid->getName().'</td>
                    <td>'.$grid->getShortDescription().'</td>
                  </tr>';
    }
    ?>
</table>


